apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "memory-checker.name" . }}
spec:
  schedule: {{ .Values.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ include "memory-checker.serviceAccountName" . }}
          containers:
          - name: memory-checker
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            command: ["/bin/sh", "-c"]
            args:
              - |
                {{ .Values.args}}
          restartPolicy: {{ .Values.restartPolicy }}
